---
title: "STATS/CSE 780 - Homework assignment 1"
author: "Pao Zhu Vivian Hsu (Student number: 400547994)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format: pdf
editor: visual
execute:
  echo: false
  warning: false
  error: false
bibliography: A1.bib
fontsize: 11pt
geometry: 
  - margin = 1in
linestretch: 1.5
---

\newpage

```{r}
## PACKAGES ##

library(tidyverse)
library(ggplot2)
```
```{r}
## LOAD DATA ##

disposalDataRaw <- read_csv(file="NPRI-INRP_DisposalsEliminations_1993-present.csv", locale=locale(encoding="latin1"))
naicsCodes <- read_csv(file="naics-scian-2017-structure-v3-eng.csv")
```


```{r}
## DATA CLEANSING ##

# Only keep asbestos waste data
disposalData <- disposalDataRaw %>%
  filter(`CAS_Number / No_CAS` == "1332-21-4") %>% 
  mutate("Quantity (Tonnes)" = if_else(`Units / Unités` == "kg", `Quantity / Quantité`/1000,`Quantity / Quantité`)) %>%
  group_by(`Reporting_Year / Année`,
           `CAS_Number / No_CAS`,
           `Substance Name (English) / Nom de substance (Anglais)`,
           `NAICS / Code_SCIAN`,
           `NAICS Title / Titre Code_SCIAN`,
           `PROVINCE`) %>%
  summarize("Quantity (Tonnes)" = sum(`Quantity (Tonnes)`)) %>%
  ungroup() %>% 
  mutate("NAICS Code (3-digit)" = substr(`NAICS / Code_SCIAN`, 1, 3)) %>% 
  left_join(naicsCodes, by = c("NAICS Code (3-digit)" = "Code")) %>% 
  select(`CAS_Number / No_CAS`,
         `Substance Name (English) / Nom de substance (Anglais)`,
         `Reporting_Year / Année`,
         `PROVINCE`,
         `NAICS / Code_SCIAN`,
         `NAICS Title / Titre Code_SCIAN`,
         `NAICS Code (3-digit)`,
         `Class title`,
         `Quantity (Tonnes)`) %>% 
  rename("CAS_Number" = `CAS_Number / No_CAS`,
         "Substance" = `Substance Name (English) / Nom de substance (Anglais)`,
         "Year" = `Reporting_Year / Année`,
         "Province" = `PROVINCE`,
         "NAICS Code (6-digit)" = `NAICS / Code_SCIAN`,
         "NAICS Category (6-digit)" = `NAICS Title / Titre Code_SCIAN`,
         "NAICS Category (3-digit)" = `Class title`)
```

```{r}
## WASTE QUANTITY BY PROVINCE AND YEAR ##

# Preliminary data transformation
disposalData_line <- disposalData %>% 
  group_by(`Year`,`Province`) %>%
  summarize("Quantity (Tonnes)" = sum(`Quantity (Tonnes)`))

# Plot line graph
disposalData_line %>% 
  ggplot(aes(x=`Year`, y=`Quantity (Tonnes)`, color=`Province`)) +
  geom_line()
```

```{r}
## WASTE QUANTITY BY YEAR AGGREGATED TO COUNTRY-LEVEL ##

# Preliminary data transformation
disposalData_line <- disposalData %>% 
  group_by(`Year`) %>%
  summarize("Quantity (Tonnes)" = sum(`Quantity (Tonnes)`))

# Plot line graph
disposalData_line %>% 
  ggplot(aes(x=`Year`, y=`Quantity (Tonnes)`)) +
  geom_line()
```

## Introduction

## Methods

## Results

## Discussion

\newpage

## Supplementary material

\newpage

## References
